name: demo workflow
on: 
  push:
    paths: 
      - '/demofile001.txt'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: test workflow
      run: echo "demo workflow test"
    - name: list files
      run: ls -lart
