name: demo workflow
on:
  workflow_dispatch:
    
  push:
    paths: 
      - '**/demofile001.txt'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: test workflow
      run: echo "demo workflow test"
    - name: list files
      run: ls -lart
