name: demo workflow
on:
  workflow_dispatch:

  push:
    paths: 
      - '**/demo.tfvars'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: test workflow
      run: echo "demo workflow test"
    - name: list files
      run: ls -lart
    - name : commit details
      run: |
        echo "Commit SHA: ${{ github.sha }}"
        echo "Commit Message: ${{ github.event.head_commit.message }}"
    - name: git changed files
      run: |
        git fetch origin ${{ github.event.before }}
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.tfvars$' || echo "No .tfvars file changed"
    - name: show line by line changes
      run: |
        mkdir -p tfvars_changes
        git diff ${{ github.event.before }} ${{ github.sha }} -- '*.tfvars' || echo "No tfvars changes"
        grep '^+[^+]' tfvars_changes/full_diff.txt > tfvars_changes/added_lines.txt
        echo "Changed lines saved in tfvars_changes/added_lines.txt"
        cat tfvars_changes/added_lines.txt
